services:
  avestruz-server:
    build:
      context: .
    entrypoint: ["/bin/avestruz", "--driver", "postgresql", "--dburl", "postgres://user:password@postgres:5432/events?sslmode=disable", "--port", "3334"] 
    ports:
      - "3334:3334"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - avestruz
  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: events
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - avestruz

volumes:
  postgres_data:

networks:
  avestruz:
